name: Example
description: Example description
body:
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: Check all that apply
      multiple: true
      options:
        - dart
        - Android
        - iOS
        - macOS
        - Web
        - Windows
        - Linux
    validations:
      required: true
