name: Discussions
description: Discussions
title: "[Discussions] "
labels:
  - "Type: Discussions"
  - "Status: Unconfirmed"
assignees:
  - zmtzawqlp
body:
  - type: markdown
    attributes:
      value: |
        First check whether the project has Discussions enabled.
        If so, it is recommended to use Discussions to create discussions.
        The discussions is here:
        [Discussions](https://github.com/FlutterCandies/[repo]/discussions)
  - type: textarea
    id: content
    attributes:
      label: Content
      description: No, I don't like to say this in the discussion area.
